name: Continous Deployment  
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'

        - run: npm install .g surge
        - run: echo "Deploying website"
        - run: surge ./ ${{ secrets.SURGE.DOMAIN  }}  --token ${{ secrets.SURGE_TOKEN  }}

        -run: echo "Please visit => ${{ secrets.SURGE_DOMAIN  }}"